version: '3.8'
services:
  api:
    build: ./api
    container_name: api_backend
    env_file:
      - ./api/.env
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true